spring.application.name=spring-security

# Setting Username and password

spring.security.user.name=cherry
spring.security.user.password=alright

# Adding DataBase

spring.datasource.url=postgresurl
spring.datasource.username=postgres
spring.datasource.password=password
